# Generated by Django 2.1.7 on 2019-04-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addcategory',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('catnm', models.CharField(max_length=50)),
                ('catdisc', models.CharField(max_length=100)),
                ('caticon', models.CharField(max_length=100)),
            ],
        ),
    ]
