# Generated by Django 2.1.7 on 2019-04-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addsubcat',
            fields=[
                ('subcatid', models.AutoField(primary_key=True, serialize=False)),
                ('subcatnm', models.CharField(max_length=50)),
                ('catnm', models.CharField(max_length=50)),
                ('subcaticon', models.CharField(max_length=1000)),
            ],
        ),
    ]
