# Generated by Django 2.1.7 on 2019-04-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_addsubcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsubcat',
            name='subcaticon',
            field=models.CharField(max_length=100),
        ),
    ]
