# Generated by Django 2.1.7 on 2019-04-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_auto_20190411_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managemenu',
            fields=[
                ('mealid', models.AutoField(primary_key=True, serialize=False)),
                ('mealnm', models.CharField(max_length=50)),
                ('mealprice', models.CharField(max_length=50)),
                ('mealdisc', models.CharField(max_length=50)),
                ('mealimg', models.CharField(max_length=50)),
                ('mealcatnm', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Managepackages',
            fields=[
                ('packid', models.AutoField(primary_key=True, serialize=False)),
                ('packnm', models.CharField(max_length=50)),
                ('packprice', models.CharField(max_length=50)),
                ('packdisc', models.CharField(max_length=50)),
                ('packimag', models.CharField(max_length=50)),
                ('packduration', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='addcategory',
            name='catdisc',
            field=models.CharField(max_length=1000),
        ),
    ]
