# Generated by Django 2.1.7 on 2019-04-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('regid', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('select_city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
